import React from 'react'

export default function Panel() {
  return (
    <div>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
      <h4>Panel</h4>
    </div>
  )
}
